name: Test the upcoming changes

on:
  push:
    branches-ignore:
      - main

jobs:
  dev:
    env:
      LABPASSPHRASE: ${{ secrets.LABPASSPHRASE }} # Not in use
    timeout-minutes: 15
    runs-on: macos-latest
    # runs-on: ubuntu-latest
    steps:
      - name: Hi
        run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install Python requirements
        run: | 
          pip3 install -r requirements.txt

      - name: Run pre-commit on files
        uses: pre-commit/action@v3.0.0

      - name: Check paths for inventory/MPLS_network
        uses: dorny/paths-filter@v2
        id: filter-site
        with:
          filters: |
            workflows:
              - 'inventory/MPLS_network/**'

      # - name: Check paths for sites/site_2
      #   uses: dorny/paths-filter@v2
      #   id: filter-site2
      #   with:
      #     filters: |
      #       workflows:
      #         - 'sites/site_2/**'

      - name: Install collections
        run: ansible-galaxy collection install -r requirements.yml
        if: steps.filter-site.outputs.workflows == 'true' 

      - name: Test configuration for inventory/MPLS_network
        shell: sh
        run: make fabric-build
        if: steps.filter-site.outputs.workflows == 'true'

      # - name: Test configuration for site2
      #   run: make build-site-2
      #   if: steps.filter-site2.outputs.workflows == 'true'
